apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: mysqlversion5
    readOnly: false
  claimRef:
    namespace: default
    name: mysql-pv-claim