apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  azureFile:
    secretName: azure-secret
    shareName: wordpressversion5
    readOnly: false
  claimRef:
    namespace: default
    name: wp-pv-claim